version: '3'

# Reminders / notes
# - You can use `npm version {major|minor|patch} --no-git-tag-version` to bump version

tasks:
  lint:
    sources:
      - cli.ts
      - common/**/*
      - vendor/**/*
      - tsconfig.json
      - package-lock.json
      - .prettier*
    cmds:
      - npx tsc --noEmit
      - npx prettier --check .
  build:
    sources:
      - cli.ts
      - common/**/*
      - vendor/**/*
      - tsconfig.json
      - package-lock.json
    cmd: |
      # Patch version
      VERSION_STRING=$(node -p "require('./package.json').version")
      echo "export const VERSION_STRING = '$VERSION_STRING';" > common/version.ts
      rm -rf dist
      mkdir dist
      npx tsc
      copy_paths=(
        'package.json'
        'package-lock.json'
        'LICENSE'
        'README.md'
      )
      for file_path in ${copy_paths[@]}; do
        cp $file_path "dist/${file_path}"
      done
  install:local:
    desc: |
      Uses `npm link` to globally share this local dev version of the package across
      your system.

      In another folder / project, you can use `npm link jtz-time-tracker-utils` to then
      pull in this linked version.
    deps: [build]
    cmd: cd dist && npm link
  uninstall:local: npm uninstall --global jtz-time-tracker-utils
  release:
    cmds:
      - task build
      - |
        cd dist
        npm pack --dry-run
        package_version=$(cat package.json | jq ".version")
        package_lock_version=$(cat package-lock.json | jq ".version")
        if [[ $package_version != $package_lock_version ]]; then
          echo "🚨 ERROR 🚨 - package.json version does not match package-lock.json version"
          exit 1
        fi
        while true; do
          read -p "🚨 WARNING 🚨 - you are about to publish version ${package_version}. Are you sure? [Yy]es, [Nn]o / [Cc]ancel" ync
          case $ync in
            [Yy]* ) break;;
            [Nn]* ) exit;;
            [Cc]* ) exit;;
          esac
        done
        npm publish
  vendor:harvest:
    desc: |
      Pulls updated type-definitions from the `node-harvest` package and
      vendors them into the package.
    dir: vendor/node-harvest
    cmds:
      - npx degit https://github.com/simplyspoke/node-harvest/src/models
      - prettier --write .
      # TODO: Fix up imports
  local: npx ts-node --esm --transpile-only ./cli.ts {{.CLI_ARGS}}
